const options = {
    typeOfLearner : [
        "Handled Youngster under 4 years",
        "Unhandled Youngster under 4 years",
        "Unhandled or semi-feral under 4 years",
        "Unhandled or semi-feral over 4 years",
        "Unhandleable, extremely fearful or known trauma",
        "Handled on the farm",
        "Previous skills but new to farm",
        "Ridden potential",
        "Ridden tickover",
        "Companion Tickover / Maintenance",
        "Sanctuary Tickover / Maintenance",
        "Sactuary Frequent Handling"
    ],
    adminActions : [
        {
            title: 'Equines',
            buttonTitle: 'Equine',
            newLink: '/equines/add-equine',
            editLink: '/equines/edit-equine',
            deleteLink: '/equines/delete-equine',
            newVariant: 'contained',
            editVariant: 'outlined',
            deleteVariant: 'outlined',
            seeAllVariant: 'green',
            newSize: 'large',
            editSize: 'large',
            deleteSize: 'small',
            seeAllLink: '/equines'
        },
        {
            title: 'Skills',
            buttonTitle: 'Skill',
            newLink: '/skills/add-skill',
            editLink: '/skills/edit-skill',
            deleteLink: '/skills/delete-skill',
            newVariant: 'contained',
            editVariant: 'outlined',
            deleteVariant: 'outlined',
            seeAllVariant: 'green',
            newSize: 'large',
            editSize: 'large',
            deleteSize: 'small',
            seeAllLink: '/skills'
        },
        {
            title: 'Yards',
            buttonTitle: 'Yard',
            newLink: '/yards/add-yard',
            editLink: '/yards/edit-yard',
            deleteLink: '/yards/delete-yard',
            newVariant: 'contained',
            editVariant: 'outlined',
            deleteVariant: 'outlined',
            seeAllVariant: 'green',
            newSize: 'large',
            editSize: 'large',
            deleteSize: 'small',
            seeAllLink: '/yards'
        },
        {
            title: 'Distruptions',
            buttonTitle: 'Distruption',
            newLink: '/distruptions/add-distruption',
            editLink: '/distruptions/edit-distruption',
            deleteLink: '/distruptions/delete-distruption',
            newVariant: 'contained',
            editVariant: 'outlined',
            deleteVariant: 'outlined',
            seeAllVariant: 'green',
            newSize: 'large',
            editSize: 'large',
            deleteSize: 'small',
            seeAllLink: '/distruptions'
        },
        {
            title: 'Training Methods',
            buttonTitle: 'Training Method',
            newLink: '/training-methods/add-training-method',
            editLink: '/training-methods/edit-training-method',
            deleteLink: '/training-methods/delete-training-method',
            newVariant: 'contained',
            editVariant: 'outlined',
            deleteVariant: 'outlined',
            seeAllVariant: 'green',
            newSize: 'large',
            editSize: 'large',
            deleteSize: 'small',
            seeAllLink: '/training-methods'
        },
        {
            title: 'Categories',
            buttonTitle: 'Category',
            newLink: '/categories/add-category',
            editLink: '/categories/edit-category',
            deleteLink: '/categories/delete-category',
            newVariant: 'contained',
            editVariant: 'outlined',
            deleteVariant: 'outlined',
            seeAllVariant: 'green',
            newSize: 'large',
            editSize: 'large',
            deleteSize: 'small',
            seeAllLink: '/categories'
        },
        {
            title: 'Environments',
            buttonTitle: 'Environment',
            newLink: '/environments/add-environment',
            editLink: '/environments/edit-environment',
            deleteLink: '/environments/delete-environment',
            newVariant: 'contained',
            editVariant: 'outlined',
            deleteVariant: 'outlined',
            seeAllVariant: 'green',
            newSize: 'large',
            editSize: 'large',
            deleteSize: 'small',
            seeAllLink: '/environments'
        },
        {
            title: 'Learner Types',
            buttonTitle: 'Learner Type',
            newLink: '/learner-types/add-learner-type',
            editLink: '/learner-types/edit-learner-type',
            deleteLink: '/learner-types/delete-learner-type',
            newVariant: 'contained',
            editVariant: 'outlined',
            deleteVariant: 'outlined',
            seeAllVariant: 'green',
            newSize: 'large',
            editSize: 'large',
            deleteSize: 'small',
            seeAllLink: '/learner-types'
        }
    ]
}

export default options;