const options = {
	typeOfLearner: [
		"Handled Youngster under 4 years",
		"Unhandled Youngster under 4 years",
		"Unhandled or semi-feral under 4 years",
		"Unhandled or semi-feral over 4 years",
		"Unhandleable, extremely fearful or known trauma",
		"Handled on the farm",
		"Previous skills but new to farm",
		"Ridden potential",
		"Ridden tickover",
		"Companion Tickover / Maintenance",
		"Sanctuary Tickover / Maintenance",
		"Sactuary Frequent Handling",
	],
	adminActions: [
		{
			title: "Equines",
			buttonTitle: "Equine",
			link: "/admin/equines",
			newLink: "/admin/equines/add-equine",
			editLink: "/admin/equines/edit-equine",
			deleteLink: "/admin/equines/delete-equine",
			newVariant: "contained",
			editVariant: "outlined",
			deleteVariant: "outlined",
			seeAllVariant: "green",
			newSize: "large",
			editSize: "large",
			deleteSize: "small",
			seeAllLink: "/equines",
		},
		{
			title: "Skills",
			buttonTitle: "Skill",
			link: "/admin/skills",
			newLink: "/admin/skills/add-skill",
			editLink: "/admin/skills/edit-skill",
			deleteLink: "/admin/admin/skills/delete-skill",
			newVariant: "contained",
			editVariant: "outlined",
			deleteVariant: "outlined",
			seeAllVariant: "green",
			newSize: "large",
			editSize: "large",
			deleteSize: "small",
			seeAllLink: "/skills",
		},
		{
			title: "Yards",
			buttonTitle: "Yard",
			link: "/admin/yards",
			newLink: "/admin/yards/add-yard",
			editLink: "/admin/yards/edit-yard",
			deleteLink: "/admin/yards/delete-yard",
			newVariant: "contained",
			editVariant: "outlined",
			deleteVariant: "outlined",
			seeAllVariant: "green",
			newSize: "large",
			editSize: "large",
			deleteSize: "small",
			seeAllLink: "/yards",
		},
		{
			title: "Disruptions",
			buttonTitle: "Disruption",
			link: "/admin/disruptions",
			newLink: "/admin/disruptions/add-disruption",
			editLink: "/admin/disruptions/edit-disruption",
			deleteLink: "/admin/disruptions/delete-disruption",
			newVariant: "contained",
			editVariant: "outlined",
			deleteVariant: "outlined",
			seeAllVariant: "green",
			newSize: "large",
			editSize: "large",
			deleteSize: "small",
			seeAllLink: "/disruptions",
		},
		{
			title: "Training Methods",
			buttonTitle: "Training Method",
			link: "/training-methods",
			newLink: "/admin/training-methods/add-training-method",
			editLink: "/admin/training-methods/edit-training-method",
			deleteLink: "/admin/training-methods/delete-training-method",
			newVariant: "contained",
			editVariant: "outlined",
			deleteVariant: "outlined",
			seeAllVariant: "green",
			newSize: "large",
			editSize: "large",
			deleteSize: "small",
			seeAllLink: "/training-methods",
		},
		{
			title: "Categories",
			buttonTitle: "Category",
			link: "/admin/categories",
			newLink: "/admin/ategories/add-category",
			editLink: "/admin/categories/edit-category",
			deleteLink: "/admin/categories/delete-category",
			newVariant: "contained",
			editVariant: "outlined",
			deleteVariant: "outlined",
			seeAllVariant: "green",
			newSize: "large",
			editSize: "large",
			deleteSize: "small",
			seeAllLink: "/categories",
		},
		{
			title: "Environments",
			buttonTitle: "Environment",
			link: "/admin/environments",
			newLink: "/admin/environments/add-environment",
			editLink: "/admin/environments/edit-environment",
			deleteLink: "/admin/environments/delete-environment",
			newVariant: "contained",
			editVariant: "outlined",
			deleteVariant: "outlined",
			seeAllVariant: "green",
			newSize: "large",
			editSize: "large",
			deleteSize: "small",
			seeAllLink: "/environments",
		},
		{
			title: "Handling Statuses",
			buttonTitle: "Handling Statuses",
			link: "/admin/handling-statuses",
			newLink: "/admin/handling-statuses/add",
			newVariant: "contained",
			editVariant: "outlined",
			deleteVariant: "outlined",
			seeAllVariant: "green",
			newSize: "large",
			editSize: "large",
			deleteSize: "small",
			seeAllLink: "/admin/handling-statuses",
		},
		{
			title: "Training Categories",
			buttonTitle: "Training Categories",
			link: "/admin/training-categories",
			newLink: "/admin/programmes/add",
			newVariant: "contained",
			editVariant: "outlined",
			deleteVariant: "outlined",
			seeAllVariant: "green",
			newSize: "large",
			editSize: "large",
			deleteSize: "small",
			seeAllLink: "/admin/training-categories",
		},
	],
};

export default options;
